export enum Image {
    HEROBANNER = '/images/herobanner_gradient.jpg',
    HEROBANNER_MOBILE = '/images/herobanner_mobile.jpg',
    LOGO = '/images/logo_agata_sawicka_black.png',
    LOGO_BLACK = '/images/logo_agata_sawicka_black.png',
    LOGO_WHITE = '/images/logo_agata_sawicka_white.png',
    BOOKSY_LOGO = '/images/booksy_logo.png',
    BOOKSY_SHORT_LOGO = '/images/booksy_short_logo.svg',
    BOOKSY_SHORT_LOGO_WHITE = '/images/booksy_short_logo_white.svg',
    BOOKSY_SHORT_LOGO_BROWN = '/images/booksy_short_logo_brown.svg',
    GOOGLE_LOGO = '/images/google_g_logo.png',
    ABOUT_ME = '/images/about_me.png',
    STUDIO_SMALLER = '/images/studio_smaller.jpg',
    STUDIO_REVIEWS_MOBILE = '/images/studio_reviews_mobile_2.jpg',
    STUDIO = '/images/studio.jpeg',
    PORTFOLIO_1 = '/images/portfolio_1.png',
    PORTFOLIO_2 = '/images/portfolio_2.png',
    PORTFOLIO_3 = '/images/portfolio_3.png',
    VOUCHER_1 = '/images/voucher_1.png',
    VOUCHER_2 = '/images/voucher_2.png',
    CONTACT_FORM_PHOTO = '/images/contact_form_photo.png',
    CONTACT_FORM_BACKGROUND = '/images/contact_background.jpg',
    GOOGLE_MAPS_LINK = '/images/google_map.png'
}